"""FastAPI app for the BioStack 4 read-only status service.

Endpoints (spec-mandated only):

* ``GET /``         - identity probe (``ProbeResponse``)
* ``GET /health``   - liveness (``HealthResponse``)
* ``GET /status``   - ``EquipmentStatus`` envelope (side-effect-free)
* ``GET /openapi.json`` - generated by FastAPI

This service publishes ``protocol_version: "1.0"`` — the read-only
baseline. There are no ``/control/*`` routes, no claim protocol, and
``allowed_actions`` is empty in every state, so reporting ``"1.1"``
would be dishonest (the v1.1 checklist mandates claim endpoints). The
dashboard's read-only aggregator picks this up via the
``ac-organic-lab/equipment.yaml`` entry (``adapter: http``); set that
entry's ``protocol: "1.0"`` to match until control lands.

A follow-up PR introduces ``/control/{startup, shutdown, home,
stage_plate, present_plate}`` along with the v1.1 claim protocol, gated
on ``PHYSICAL_TESTS.md`` sign-off.

Auth: none at the device level; access is gated by Tailscale ACLs.
CORS: wildcard by default; tighten via ``[service] cors_origins`` in
``config.toml`` if the device ever leaves the Tailnet.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from . import config as _config
from .models import (
    PROTOCOL_VERSION,
    EquipmentStatus,
    HealthResponse,
    ProbeResponse,
)
from .service import BioStack4Service

logger = logging.getLogger(__name__)


def create_app(
    *,
    dry_run: bool | None = None,
    service: BioStack4Service | None = None,
) -> FastAPI:
    """Build the FastAPI application.

    Parameters
    ----------
    dry_run:
        Force dry-run mode regardless of ``config.toml``. ``None`` means
        "use the config file". Tests pass ``True`` to keep CI hardware-free.
    service:
        Pre-built service instance. Mostly useful for tests that want to
        inject a custom transport. If omitted, ``create_app`` builds one
        from config.
    """
    cfg = _config.load_config()

    if service is None:
        if dry_run is None:
            dry_run = bool(_config.get(cfg, "service", "dry_run", False))
        service = BioStack4Service(dry_run=dry_run)

    startup_timeout = float(_config.get(cfg, "service", "startup_connect_timeout_s", 5.0))

    @asynccontextmanager
    async def lifespan(app: FastAPI):  # noqa: ARG001
        try:
            await asyncio.wait_for(service.startup(), timeout=startup_timeout)
            logger.info("BioStack 4 transport opened")
        except asyncio.TimeoutError:
            logger.warning(
                "BioStack 4 transport open timed out after %.0fs; leaving in requires_init",
                startup_timeout,
            )
        except Exception as exc:
            logger.warning("BioStack 4 transport open failed: %s", exc)
        try:
            yield
        finally:
            await service.shutdown()

    app = FastAPI(
        title="Agilent BioStack 4 Status API",
        version="0.1.0",
        description=(
            "Read-only REST API for the Agilent BioStack 4 microplate "
            "stacker. Conforms to the lab equipment status spec v1.0 "
            "(read-only baseline) - see the `docs/STATUS_SPEC.md` document "
            "in the ac-organic-lab monorepo. Control endpoints "
            "are intentionally not exposed until PHYSICAL_TESTS.md is "
            "signed off."
        ),
        lifespan=lifespan,
    )

    cors_origins: Any = _config.get(cfg, "service", "cors_origins", ["*"])
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(cors_origins),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/", response_model=ProbeResponse, tags=["spec"])
    async def probe() -> ProbeResponse:
        return ProbeResponse(
            equipment_id=service.equipment_id,
            equipment_name=service.equipment_name,
            protocol_version=PROTOCOL_VERSION,
        )

    @app.get("/health", response_model=HealthResponse, tags=["spec"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/status", response_model=EquipmentStatus, tags=["spec"])
    async def status() -> EquipmentStatus:
        return await service.get_status()

    app.state.service = service
    return app


__all__ = ["create_app"]
