"""FastAPI app for the BioStack 4 service (lab status spec v1.1).

Endpoints
---------

Spec-mandated (always available):

* ``GET /``         - identity probe (``ProbeResponse``)
* ``GET /health``   - liveness (``HealthResponse``)
* ``GET /status``   - ``EquipmentStatus`` envelope (side-effect-free)
* ``GET /openapi.json`` - generated by FastAPI

Claim protocol (v1.1; required to issue other ``/control/*`` calls when
``enforce_claims=True``):

* ``POST /control/claim``     - body ``ClaimRequest`` -> ``ClaimResponse`` / 409
* ``POST /control/heartbeat`` - header ``X-Claim-Token`` -> ``ClaimResponse`` / 401
* ``POST /control/release``   - header ``X-Claim-Token`` -> 204 (idempotent)

Control (each requires ``X-Claim-Token`` matching the live claim, else 423):

* ``POST /control/startup``        - open the serial transport (no-op if connected)
* ``POST /control/shutdown``       - close the transport
* ``POST /control/home``           - home all axes
* ``POST /control/stage_plate``    - input stack -> internal handoff (``b9``)
* ``POST /control/present_plate``  - handoff -> external drop-off (``cd``);
  **412 unless a plate is staged** (the latch guard, see ``service.py`` §3)
* ``POST /control/handoff``        - stage then present in one server-side op;
  the present-a-plate primitive that is structurally incapable of latching

Auth: none at the device level; access is gated by Tailscale ACLs. The
claim protocol provides *coordination*, not authentication.
CORS: wildcard by default; tighten via ``[service] cors_origins`` in
``config.toml`` if the device ever leaves the Tailnet.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Annotated, Any

from fastapi import Depends, FastAPI, Header, HTTPException, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from . import config as _config
from .claims import ClaimConflict, UnknownClaim
from .exceptions import NoPlatePickedUpError, StackEmptyError
from .models import (
    PROTOCOL_VERSION,
    ClaimRejection,
    ClaimRequest,
    ClaimResponse,
    EquipmentStatus,
    HealthResponse,
    ProbeResponse,
)
from .service import (
    BioStack4Service,
    DeviceStateError,
    StagePreconditionError,
)

logger = logging.getLogger(__name__)


class CommandResponse(BaseModel):
    ok: bool = True
    message: str | None = None


class _ClaimResponseException(Exception):
    """Raised when the API needs to emit a top-level JSON body with a
    custom HTTP status. Caught by the registered exception handler.

    FastAPI's ``HTTPException`` always wraps the detail in ``{"detail": ...}``;
    the v1.1 spec requires claim rejections (409/423) and precondition
    refusals (412) to sit at the *top level* so clients can branch on the
    body shape (``response.json()["claimed_by"]`` / ``["plate_staged"]``).
    """

    def __init__(
        self,
        status_code: int,
        payload: dict[str, Any],
        headers: dict[str, str] | None = None,
    ) -> None:
        super().__init__(f"HTTP {status_code}")
        self.status_code = status_code
        self.payload = payload
        self.headers = headers or {}


def create_app(
    *,
    dry_run: bool | None = None,
    enforce_claims: bool | None = None,
    enforce_stage_precondition: bool | None = None,
    service: BioStack4Service | None = None,
) -> FastAPI:
    """Build the FastAPI application.

    Parameters
    ----------
    dry_run:
        Force dry-run mode regardless of ``config.toml``. ``None`` means
        "use the config file". Tests pass ``True`` to keep CI hardware-free.
    enforce_claims:
        Strict v1.1 enforcement of ``X-Claim-Token`` on ``/control/*``.
        ``None`` -> config (default ``True``). Emergency-only override.
    enforce_stage_precondition:
        The staged-plate interlock (§6.1). ``None`` -> config (default
        ``True``). Emergency-only override; disabling it makes the latch
        trap reachable through the API.
    service:
        Pre-built service instance (mostly for tests injecting a transport).
        If omitted, ``create_app`` builds one from config + the flags above.
    """
    cfg = _config.load_config()

    if service is None:
        if dry_run is None:
            dry_run = bool(_config.get(cfg, "service", "dry_run", False))
        if enforce_claims is None:
            enforce_claims = bool(_config.get(cfg, "service", "enforce_claims", True))
        if enforce_stage_precondition is None:
            enforce_stage_precondition = bool(
                _config.get(cfg, "service", "enforce_stage_precondition", True)
            )
        service = BioStack4Service(
            dry_run=dry_run,
            enforce_claims=enforce_claims,
            enforce_stage_precondition=enforce_stage_precondition,
        )

    startup_timeout = float(_config.get(cfg, "service", "startup_connect_timeout_s", 5.0))

    @asynccontextmanager
    async def lifespan(app: FastAPI):  # noqa: ARG001
        try:
            await asyncio.wait_for(service.startup(), timeout=startup_timeout)
            logger.info("BioStack 4 transport opened")
        except asyncio.TimeoutError:
            logger.warning(
                "BioStack 4 transport open timed out after %.0fs; leaving in requires_init",
                startup_timeout,
            )
        except Exception as exc:
            logger.warning("BioStack 4 transport open failed: %s", exc)
        try:
            yield
        finally:
            try:
                await service.claims.force_clear()
            except Exception:
                logger.exception("Error while clearing claim on shutdown")
            await service.shutdown()

    app = FastAPI(
        title="Agilent BioStack 4 API",
        version="0.2.0",
        description=(
            "REST API for the Agilent BioStack 4 microplate stacker. "
            "Conforms to the AC lab equipment status spec v1.1 (claims, "
            "allowed_actions, details.claimed_by) - see `docs/STATUS_SPEC.md` "
            "in the ac-organic-lab monorepo. The motion surface is guarded "
            "by a staged-plate precondition so `present_plate` (cd) can never "
            "be issued into an empty handoff (the sticky latch)."
        ),
        lifespan=lifespan,
    )

    cors_origins: Any = _config.get(cfg, "service", "cors_origins", ["*"])
    app.add_middleware(
        CORSMiddleware,
        allow_origins=list(cors_origins),
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.exception_handler(_ClaimResponseException)
    async def _claim_response_handler(
        request: Request, exc: _ClaimResponseException
    ) -> JSONResponse:  # noqa: ARG001
        return JSONResponse(
            status_code=exc.status_code,
            content=exc.payload,
            headers=exc.headers,
        )

    # ---- Spec endpoints ---------------------------------------------------

    @app.get("/", response_model=ProbeResponse, tags=["spec"])
    async def probe() -> ProbeResponse:
        return ProbeResponse(
            equipment_id=service.equipment_id,
            equipment_name=service.equipment_name,
            protocol_version=PROTOCOL_VERSION,
        )

    @app.get("/health", response_model=HealthResponse, tags=["spec"])
    async def health() -> HealthResponse:
        return HealthResponse()

    @app.get("/status", response_model=EquipmentStatus, tags=["spec"])
    async def status() -> EquipmentStatus:
        return await service.get_status()

    # ---- Claim protocol (v1.1) -------------------------------------------

    async def require_claim(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> None:
        """Gate every ``/control/*`` macro with the live claim token.

        No-op when the service was built with ``enforce_claims=False``
        (advisory mode: tokens still issued, ``claimed_by`` still published,
        but writes are not blocked). Runs as a dependency so a tokenless
        request 423s *ahead of* any 412 precondition check.
        """
        if not service.enforce_claims:
            return
        if x_claim_token is None or not await service.claims.validate(x_claim_token):
            current = await service.claims.current()
            payload: dict[str, Any] = {
                "detail": "missing or invalid X-Claim-Token; POST /control/claim first",
                "claimed_by": (
                    current.model_dump(mode="json") if current is not None else None
                ),
                "retry_after_s": None,
            }
            raise _ClaimResponseException(status_code=423, payload=payload)

    @app.post(
        "/control/claim",
        response_model=ClaimResponse,
        responses={409: {"model": ClaimRejection}},
        tags=["claim"],
    )
    async def control_claim(req: ClaimRequest) -> ClaimResponse:
        try:
            return await service.claims.acquire(req)
        except ClaimConflict as exc:
            rejection = ClaimRejection(
                detail=str(exc),
                claimed_by=exc.claimed_by,
                retry_after_s=exc.retry_after_s,
            )
            raise _ClaimResponseException(
                status_code=409,
                payload=rejection.model_dump(mode="json"),
                headers={"Retry-After": str(int(exc.retry_after_s + 1))},
            )

    @app.post("/control/heartbeat", response_model=ClaimResponse, tags=["claim"])
    async def control_heartbeat(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> ClaimResponse:
        try:
            return await service.claims.heartbeat(x_claim_token)
        except UnknownClaim:
            raise HTTPException(
                status_code=401,
                detail="claim token is unknown or expired; POST /control/claim",
            )

    @app.post("/control/release", status_code=204, tags=["claim"])
    async def control_release(
        x_claim_token: Annotated[str | None, Header(alias="X-Claim-Token")] = None,
    ) -> Response:
        await service.claims.release(x_claim_token)
        return Response(status_code=204)

    # ---- Control endpoints (guarded macros) ------------------------------

    def _control_error(exc: Exception) -> _ClaimResponseException | HTTPException:
        """Map a control-path exception to its HTTP response.

        * ``StagePreconditionError`` -> 412 with the shape-distinguishable
          body. (412 MUST NOT mutate ``last_error`` — the service raises
          this *before* ``to_thread`` so it never records one, per §6.3.)
        * ``DeviceLatchedError`` / ``DeviceStateError`` -> 409.
        * ``StackEmptyError`` -> 409 (graceful, recoverable: add plates).
        * ``NoPlatePickedUpError`` -> 409 (the device just latched;
          ``service`` has set ``last_error`` + ``equipment_status: error``).
        * Anything else -> 500.
        """
        if isinstance(exc, StagePreconditionError):
            return _ClaimResponseException(status_code=412, payload=exc.body)
        if isinstance(exc, StackEmptyError):
            return HTTPException(
                status_code=409,
                detail=f"Input stack empty; nothing to stage ({exc})",
            )
        if isinstance(exc, NoPlatePickedUpError):
            return HTTPException(
                status_code=409,
                detail=(
                    "BioStack latched: no plate was at the handoff. Power-cycle "
                    "the device and inspect the carrier for a jam."
                ),
            )
        if isinstance(exc, DeviceStateError):  # includes DeviceLatchedError
            return HTTPException(status_code=409, detail=str(exc))
        return HTTPException(status_code=500, detail=str(exc))

    @app.post("/control/startup", response_model=CommandResponse, tags=["control"])
    async def control_startup(_claim: None = Depends(require_claim)) -> CommandResponse:
        try:
            await service.startup()
        except Exception as exc:
            raise HTTPException(status_code=503, detail=str(exc))
        return CommandResponse(message="Connected")

    @app.post("/control/shutdown", response_model=CommandResponse, tags=["control"])
    async def control_shutdown(_claim: None = Depends(require_claim)) -> CommandResponse:
        await service.shutdown()
        return CommandResponse(message="Disconnected")

    @app.post("/control/home", response_model=CommandResponse, tags=["control"])
    async def control_home(_claim: None = Depends(require_claim)) -> CommandResponse:
        try:
            await service.home()
        except Exception as exc:
            raise _control_error(exc)
        return CommandResponse(message="Homed")

    @app.post(
        "/control/stage_plate",
        response_model=CommandResponse,
        responses={412: {"description": "A plate is already staged at the handoff."}},
        tags=["control"],
    )
    async def control_stage_plate(
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.stage_plate()
        except Exception as exc:
            raise _control_error(exc)
        return CommandResponse(message="Plate staged at the handoff")

    @app.post(
        "/control/present_plate",
        response_model=CommandResponse,
        responses={
            412: {
                "description": (
                    "No plate staged at the handoff. Refused so `cd` is never "
                    "issued into an empty handoff (the sticky latch)."
                )
            }
        },
        tags=["control"],
    )
    async def control_present_plate(
        _claim: None = Depends(require_claim),
    ) -> CommandResponse:
        try:
            await service.present_plate()
        except Exception as exc:
            raise _control_error(exc)
        return CommandResponse(message="Plate presented to the external drop-off")

    @app.post(
        "/control/handoff",
        response_model=CommandResponse,
        responses={412: {"description": "A plate is already staged at the handoff."}},
        tags=["control"],
    )
    async def control_handoff(_claim: None = Depends(require_claim)) -> CommandResponse:
        try:
            await service.handoff()
        except Exception as exc:
            raise _control_error(exc)
        return CommandResponse(message="Plate staged and presented")

    app.state.service = service
    return app


__all__ = ["create_app"]
